### ISSUE TITLE
Is there long term value in wargo?

### ISSUE THREAD

**Issue by ColinEberhardt** [lord/wargo#22]
Thanks for your work on wargo, this sort of project makes it much easier for the rest of us to experiment with WebAssembly!

Now that the rust compiler has [moved to using LLVM rather than Emscripten / fastcomp](https://github.com/rust-lang/rust/pull/45905) - I can now build wasm modules, with dependencies, as follows:

~~~
cargo +nightly build --release --target wasm32-unknown-unknown
~~~

Does this mean wargo is no longer needed?

**Comment by lord** [comment]
I mean, it's not needed if you're using `wasm-unknown-unknown`, which is a good thing, since it means it's gotten much easier! Still, if you want to use Emscripten and its various APIs, it should still be helpful perhaps.
