### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by demurgos** [lord/wargo#4]
Hi,
Could you add an example project demonstrating how to use _wargo_?

I am still trying to figure out how to use Wasm with Rust. I'm mostly interested in just exposing a Wasm lib (without `main`, it will just be called by Javascript).

**Comment by lord** [comment]
@demurgos [Ian's medium post](https://medium.com/@ianjsikes/get-started-with-rust-webassembly-and-webpack-58d28e219635) has some helpful code, and I just made [wargo-loader-example](https://github.com/lord/wargo-loader-example) that shows how to call a function. How does that look?

**Comment by demurgos** [comment]
Thank you very much.

The post you linked helped me to start, but I am struggling to go past this hello world example. I am more looking for some medium-sized examples: ideally a small/medium sized real-world library using Rust to compile to Wasm/Asm.js and published to npm. This may be too specific so any other example would be nice: I just feel that there are not enough examples.

I posted a longer description of the questions I currently have regarding Rust and Wasm in [this thread about Rust and Wasm](https://internals.rust-lang.org/t/state-of-webassembly-and-rust/6077/39?u=demurgos)

**Comment by lord** [comment]
These are really great questions, thanks! I'm going to close this now since we have a minimal example on how `wargo-loader` works, but I agree that these are questions that need answers.

**Comment by demurgos** [comment]
Thanks. I don't have much time right now to research all of my questions on my own but I am still very interested in the possibilities offered by Wasm. I'll keep an eye on Wargo.
