### ISSUE TITLE
Check for wasm32-unknown-emscripten rust target

### ISSUE THREAD

**Issue by killercup** [lord/wargo#5]
Wow, thanks so much for this! Wargo worked perfectly on my Mac after I ran `rustup target add wasm32-unknown-emscripten`. I think you're already checking for rustup, maybe you can have the setup add the target as well?

**Comment by lord** [comment]
Whoops, looks like we're auto-adding it on Linux but not macOS. Just fixed this in master, and I'll cut a new release soon. Thanks for the catch!
